name: pbc_mindist
channels:
  - omnia
  - defaults
dependencies:
  - blas=1.0=mkl
  - blosc=1.15.0=hd408876_0
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py36_0
  - cython=0.29.7=py36he6710b0_0
  - hdf5=1.10.4=hb1b8bf9_0
  - intel-openmp=2019.3=199
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - lzo=2.10=h49e0be7_2
  - mkl=2019.3=199
  - mkl_fft=1.0.12=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - numexpr=2.6.9=py36h9e4a6bb_0
  - numpy=1.16.3=py36h7e9f1db_0
  - numpy-base=1.16.3=py36hde5b4d6_0
  - openssl=1.1.1b=h7b6447c_1
  - pandas=0.24.2=py36he6710b0_0
  - pip=19.1.1=py36_0
  - pytables=3.5.1=py36h71ec239_0
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2019.1=py_0
  - readline=7.0=h7b6447c_5
  - scipy=1.2.1=py36h7c811a0_0
  - setuptools=41.0.1=py36_0
  - six=1.12.0=py36_0
  - snappy=1.1.7=hbae5bb6_3
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.4=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - fftw3f=3.3.4=2
  - mdtraj=1.9.1=py36_0
  - openmm=7.3.1=py36_cuda92_rc_2

